import type { FrameVariant } from './types.ts'
import type { FrameFamily, FrameFamilyId, FrameLayout } from './frameFamilies.ts'

const commonFonts = [
	'70px belerenb',
	'70px belerenbsc',
	'64px mplantin',
	'64px mplantini',
]

const commonFallbacks: Partial<Record<FrameVariant, FrameVariant>> = {
	V: 'A',
	WL: 'L',
	UL: 'L',
	BL: 'L',
	RL: 'L',
	GL: 'L',
	ML: 'L',
	WU: 'M',
	WB: 'M',
	UB: 'M',
	UR: 'M',
	BR: 'M',
	BG: 'M',
	RG: 'M',
	RW: 'M',
	GW: 'M',
	GU: 'M',
}

const m15Pt = {
	W: 'img/frames/m15/regular/m15PTW.png',
	U: 'img/frames/m15/regular/m15PTU.png',
	B: 'img/frames/m15/regular/m15PTB.png',
	R: 'img/frames/m15/regular/m15PTR.png',
	G: 'img/frames/m15/regular/m15PTG.png',
	M: 'img/frames/m15/regular/m15PTM.png',
	A: 'img/frames/m15/regular/m15PTA.png',
	C: 'img/frames/m15/regular/m15PTC.png',
	V: 'img/frames/m15/regular/m15PTV.png',
}

const commonFooter: FrameLayout['footer'] = {
	x: 115,
	maxWidth: 1050,
	metadataY: 1985,
	metadata: { font: '38px mplantin, serif', color: '#fff' },
	disclaimerY: 2025,
	disclaimer: { font: '34px mplantin, serif', color: '#fff' },
}

function tokenFrames(style: string, variants: readonly FrameVariant[]): FrameFamily['frames'] {
	return Object.fromEntries(variants.map((variant) => [variant, `img/frames/token/${style}/${variant.toLowerCase()}.png`]))
}

const m15RegularLayout: FrameLayout = {
	artwork: { dragTop: 237, dragBottom: 1167 },
	title: { x: 125, y: 165, maxWidth: 1244, font: '70px belerenb, serif', color: '#111' },
	mana: { right: 1391, centerY: 167, symbolSize: 64, gap: 4, font: '48px belerenb, serif', color: '#111' },
	type: { x: 125, y: 1242, maxWidth: 1244, font: '54px belerenb, serif', color: '#111' },
	rules: { x: 129, y: 1328, width: 1242, height: 604, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
	symbol: { centerX: 1335, centerY: 1241, boxSize: 85 },
	pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1292, textY: 1933, font: '70px belerenbsc, serif', color: '#111' },
	footer: commonFooter,
}

const tokenRegularLayout: FrameLayout = {
	artwork: { dragTop: 60, dragBottom: 1439 },
	title: { x: 120, y: 163, maxWidth: 1265, align: 'center', font: '80px belerenb, serif', color: '#fff' },
	mana: { right: 1316, centerY: 121, symbolSize: 70, gap: 8, font: '48px belerenb, serif', color: '#fff' },
	type: { x: 120, y: 1415, maxWidth: 1190, font: '68px belerenb, serif', color: '#111' },
	rules: { x: 130, y: 1510, width: 1240, height: 410, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
	symbol: { centerX: 1345, centerY: 1416, boxSize: 86 },
	pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1300, textY: 1935, font: '78px belerenbsc, serif', color: '#111' },
	footer: commonFooter,
}

const tokenTallLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1240 },
	type: { ...tokenRegularLayout.type, y: 1240 },
	rules: { ...tokenRegularLayout.rules, y: 1335, height: 585 },
	symbol: { ...tokenRegularLayout.symbol, centerY: 1241 },
}

const tokenShortLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1940 },
	type: { ...tokenRegularLayout.type, y: 1481 },
	rules: { ...tokenRegularLayout.rules, y: 1559, height: 371 },
	symbol: { ...tokenRegularLayout.symbol, centerY: 1475 },
}

const tokenTextlessLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1771 },
	type: { ...tokenRegularLayout.type, y: 1771 },
	rules: { ...tokenRegularLayout.rules, y: 0, height: 0 },
	symbol: { ...tokenRegularLayout.symbol, centerY: 1772 },
}

const tokenTextlessBorderlessLayout: FrameLayout = {
	...tokenTextlessLayout,
	artwork: { dragTop: 0, dragBottom: 2100 },
	title: { ...tokenTextlessLayout.title, x: 128, y: 167, maxWidth: 1244 },
	type: { ...tokenTextlessLayout.type, x: 128, y: 1778, maxWidth: 1244 },
	symbol: { ...tokenTextlessLayout.symbol, centerY: 1775 },
}

const tokenOldLayout: FrameLayout = {
	artwork: { dragTop: 232, dragBottom: 1303 },
	title: { x: 170, y: 150, maxWidth: 1160, align: 'center', font: '100px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	mana: { right: 1330, centerY: 106, symbolSize: 0, gap: 0, font: '48px mplantin, serif', color: '#fff' },
	type: { x: 234, y: 1425, maxWidth: 1032, font: '67px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	rules: { x: 270, y: 1496, width: 960, height: 294, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 75, minFontSize: 32 },
	symbol: { centerX: 1228, centerY: 1424, boxSize: 78 },
	pt: { x: 1040, y: 1838, width: 205, height: 90, textX: 1160, textY: 1883, font: '90px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	footer: {
		align: 'center', x: 750, maxWidth: 1200,
		metadataY: 1855, metadata: { font: '42px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 2 },
		disclaimerY: 1900, disclaimer: { font: '30px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 2, shadowOffsetY: 2 },
        disclaimerColorByVariant: { W: '#111' }
	},
}

const tokenUngluedLayout: FrameLayout = {
	artwork: { dragTop: 204, dragBottom: 1815 },
	title: { x: 0, y: 0, maxWidth: 0, font: '1px mplantin, serif', color: '#fff' },
	mana: { right: 0, centerY: 0, symbolSize: 0, gap: 0, font: '1px mplantin, serif', color: '#fff' },
	type: { x: 0, y: 0, maxWidth: 0, font: '1px mplantin, serif', color: '#fff' },
	rules: { x: 0, y: 0, width: 0, height: 0, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0, maxFontSize: 1, minFontSize: 1 },
	symbol: { centerX: 0, centerY: 0, boxSize: 0 },
	pt: { x: 0, y: 0, width: 0, height: 0, textX: 0, textY: 0, font: '1px mplantin, serif', color: '#fff' },
	footer: {
		align: 'center', x: 750, maxWidth: 1200,
		metadataY: 1900, metadata: { font: '42px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 2 },
		disclaimerY: 1955, disclaimer: { font: '30px mplantin, serif', color: '#111', shadowColor: '#111', shadowOffsetX: 2, shadowOffsetY: 2 },
        disclaimerColorByVariant: { G: '#fff', B: '#fff' }
	},
}

const tokenMonarchLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1940 },
	title: { ...tokenRegularLayout.title, y: 1383, color: '#f4ce80' },
	mana: { ...tokenRegularLayout.mana, symbolSize: 0 },
	type: { ...tokenRegularLayout.type, maxWidth: 0 },
	rules: { ...tokenRegularLayout.rules, y: 1460, height: 470 },
	symbol: { centerX: 0, centerY: 0, boxSize: 0 },
	pt: { ...tokenRegularLayout.pt, width: 0, height: 0 },
}

const tokenMarkerLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1940 },
	title: { ...tokenRegularLayout.title, y: 1481 },
	mana: { ...tokenRegularLayout.mana, symbolSize: 0 },
	type: { ...tokenRegularLayout.type, maxWidth: 0 },
	rules: { ...tokenRegularLayout.rules, y: 1559, height: 371, color: '#fff', strokeColor: '#fff' },
	symbol: { ...tokenRegularLayout.symbol, centerY: 1475 },
	pt: { ...tokenRegularLayout.pt, width: 0, height: 0 },
}

const tokenInitiativeLayout: FrameLayout = {
	...tokenMarkerLayout,
	title: { ...tokenMarkerLayout.title, y: 1247, font: '80px belerenb, serif' },
	rules: { ...tokenMarkerLayout.rules, y: 1324, height: 604 },
	symbol: { ...tokenMarkerLayout.symbol, centerY: 1241 },
}

const tokenDayNightLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 60, dragBottom: 1929 },
	mana: { ...tokenRegularLayout.mana, symbolSize: 0 },
	type: { ...tokenRegularLayout.type, maxWidth: 0 },
	rules: { ...tokenRegularLayout.rules, x: 90, y: 1300, width: 1320, height: 630, color: '#fff', strokeColor: '#fff' },
	flavorRules: { ...tokenRegularLayout.rules, x: 90, y: 266, width: 1320, height: 350, color: '#fff', strokeColor: '#fff' },
	symbol: { centerX: 0, centerY: 0, boxSize: 0 },
	pt: { ...tokenRegularLayout.pt, width: 0, height: 0 },
	footer: { ...commonFooter, metadataY: 2010, disclaimerX: 1385, disclaimerY: 2010, disclaimerAlign: 'right' },
}

const tokenJumpstartLayout: FrameLayout = {
	...tokenRegularLayout,
	artwork: { dragTop: 74, dragBottom: 2026 },
	title: { ...tokenRegularLayout.title, x: 71, y: 1570, maxWidth: 1358, font: '112px belerenb, serif' },
	mana: { ...tokenRegularLayout.mana, right: 800, centerY: 1795, symbolSize: 100 },
	type: { ...tokenRegularLayout.type, maxWidth: 0 },
	rules: { ...tokenRegularLayout.rules, height: 0 },
	symbol: { centerX: 0, centerY: 0, boxSize: 0 },
	pt: { ...tokenRegularLayout.pt, width: 0, height: 0 },
	footer: { ...commonFooter, metadataY: 2010, disclaimerY: 2040 },
}

const seventhLayout: FrameLayout = {
	artwork: { dragTop: 208, dragBottom: 1138 },
	title: { x: 170, y: 148, maxWidth: 1160, font: '80px goudymedieval, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 4, shadowOffsetY: 3 },
	mana: { right: 1386, centerY: 140, symbolSize: 68, gap: 4, font: '48px goudymedieval, serif', color: '#fff' },
	type: { x: 161, y: 1209, maxWidth: 1178, font: '65px goudymedieval, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 4, shadowOffsetY: 3 },
	rules: { x: 192, y: 1285, width: 1116, height: 565, verticalAlign: 'middle', fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 72, minFontSize: 32 },
	symbol: { centerX: 1290, centerY: 1209, boxSize: 78 },
	pt: { x: 1211, y: 1899, width: 205, height: 90, textX: 1314, textY: 1944, font: '90px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 5, shadowOffsetY: 5 },
	footer: {
		align: 'center',
		x: 750,
		maxWidth: 1200,
		metadataY: 1925,
		metadata: { font: '42px goudymedieval, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 2 },
		disclaimerY: 1975,
		disclaimer: { font: '30px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 0, shadowOffsetY: 0 },
		disclaimerColorByVariant: { W: '#111' },
	},
}

const abuFrames: FrameFamily['frames'] = {
	W: 'img/frames/old/abu/w.png', U: 'img/frames/old/abu/u.png',
	B: 'img/frames/old/abu/b.png', R: 'img/frames/old/abu/r.png',
	G: 'img/frames/old/abu/g.png', A: 'img/frames/old/abu/a.png',
	L: 'img/frames/old/abu/l.png', WL: 'img/frames/old/abu/wl.png',
	UL: 'img/frames/old/abu/ul.png', BL: 'img/frames/old/abu/bl.png',
	RL: 'img/frames/old/abu/rl.png', GL: 'img/frames/old/abu/gl.png',
}

const abuFallbacks: FrameFamily['fallbacks'] = {
	...commonFallbacks,
	C: 'A', M: 'A', ML: 'L',
	WU: 'A', WB: 'A', UB: 'A', UR: 'A', BR: 'A', BG: 'A', RG: 'A', RW: 'A', GW: 'A', GU: 'A',
}

const abuLayout: FrameLayout = {
	artwork: { dragTop: 219, dragBottom: 1145 },
	title: { x: 105, y: 150, maxWidth: 1190, font: '90px goudymedieval, serif', color: '#ababab', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	mana: { right: 1375, centerY: 157, symbolSize: 74, gap: 4, font: '48px goudymedieval, serif', color: '#ababab', shadowOffsetX: 0, shadowOffsetY: 0 },
	type: { x: 150, y: 1208, maxWidth: 1130, font: '70px mplantin, serif', color: '#ababab', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	rules: { x: 225, y: 1270, width: 1050, height: 580, verticalAlign: 'middle', fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 72, minFontSize: 32 },
	symbol: { centerX: 1325, centerY: 1225, boxSize: 74 },
	pt: { x: 1200, y: 1884, width: 240, height: 87, textX: 1320, textY: 1928, font: '87px mplantin, serif', color: '#ababab', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
	footer: {
		align: 'left', x: 150, maxWidth: 1200,
		metadataY: 1915, metadata: { font: '50px mplantin, serif', color: '#ababab', shadowColor: '#111', shadowOffsetX: 4, shadowOffsetY: 3 },
		disclaimerY: 1970, disclaimer: { font: '26px mplantin, serif', color: '#ababab', shadowColor: '#111', shadowOffsetX: 4, shadowOffsetY: 3 },
	},
}

export const FRAME_FAMILIES: Record<FrameFamilyId, FrameFamily> = {
	'planeswalker-regular': {
		id: 'planeswalker-regular',
		frames: {
			W: 'img/frames/planeswalker/regular/planeswalkerFrameW.png', U: 'img/frames/planeswalker/regular/planeswalkerFrameU.png',
			B: 'img/frames/planeswalker/regular/planeswalkerFrameB.png', R: 'img/frames/planeswalker/regular/planeswalkerFrameR.png',
			G: 'img/frames/planeswalker/regular/planeswalkerFrameG.png', M: 'img/frames/planeswalker/regular/planeswalkerFrameM.png',
			A: 'img/frames/planeswalker/regular/planeswalkerFrameA.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A', L: 'A' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1180 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1239, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1310, width: 1100, height: 560, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1237, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-borderless': {
		id: 'planeswalker-borderless',
		frames: {
			W: 'img/frames/planeswalker/borderless/w.png',
			U: 'img/frames/planeswalker/borderless/u.png',
			B: 'img/frames/planeswalker/borderless/b.png',
			R: 'img/frames/planeswalker/borderless/r.png',
			G: 'img/frames/planeswalker/borderless/g.png',
			M: 'img/frames/planeswalker/borderless/m.png',
			A: 'img/frames/planeswalker/borderless/a.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A', L: 'A' },
		layout: {
			artwork: { dragTop: 0, dragBottom: 1922 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1239, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1310, width: 1100, height: 560, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1237, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-box-topper': {
		id: 'planeswalker-box-topper',
		frames: {
			W: 'img/frames/planeswalker/box-topper/w.png',
			U: 'img/frames/planeswalker/box-topper/u.png',
			B: 'img/frames/planeswalker/box-topper/b.png',
			R: 'img/frames/planeswalker/box-topper/r.png',
			G: 'img/frames/planeswalker/box-topper/g.png',
			M: 'img/frames/planeswalker/box-topper/m.png',
			A: 'img/frames/planeswalker/box-topper/a.png',
			L: 'img/frames/planeswalker/box-topper/l.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'L' },
		layout: {
			artwork: { dragTop: 76, dragBottom: 1310 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1242, maxWidth: 1240, font: '68px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 2, shadowOffsetY: 2 },
			rules: { x: 270, y: 1310, width: 1100, height: 560, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1237, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-compleated': {
		id: 'planeswalker-compleated',
		frameOverlays: {
			W: { path: 'img/frames/planeswalker/compleated/holo/w.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
			U: { path: 'img/frames/planeswalker/compleated/holo/u.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
			B: { path: 'img/frames/planeswalker/compleated/holo/b.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
			R: { path: 'img/frames/planeswalker/compleated/holo/r.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
			G: { path: 'img/frames/planeswalker/compleated/holo/g.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
			M: { path: 'img/frames/planeswalker/compleated/holo/m.png', bounds: { x: 662, y: 1894, width: 176, height: 100 } },
		},
		frames: {
			W: 'img/frames/planeswalker/compleated/w.png',
			U: 'img/frames/planeswalker/compleated/u.png',
			B: 'img/frames/planeswalker/compleated/b.png',
			R: 'img/frames/planeswalker/compleated/r.png',
			G: 'img/frames/planeswalker/compleated/g.png',
			M: 'img/frames/planeswalker/compleated/m.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, A: 'M', C: 'M', L: 'M' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1180 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1100, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1172, width: 1100, height: 698, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1099, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-tall': {
		id: 'planeswalker-tall',
		frames: {
			W: 'img/frames/planeswalker/tall/planeswalkerTallW.png',
			U: 'img/frames/planeswalker/tall/planeswalkerTallU.png',
			B: 'img/frames/planeswalker/tall/planeswalkerTallB.png',
			R: 'img/frames/planeswalker/tall/planeswalkerTallR.png',
			G: 'img/frames/planeswalker/tall/planeswalkerTallG.png',
			M: 'img/frames/planeswalker/tall/planeswalkerTallM.png',
			A: 'img/frames/planeswalker/tall/planeswalkerTallA.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A', L: 'A' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1040 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1100, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1172, width: 1100, height: 698, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1099, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-tall-borderless': {
		id: 'planeswalker-tall-borderless',
		frames: {
			W: 'img/frames/planeswalker/tall-borderless/w.png',
			U: 'img/frames/planeswalker/tall-borderless/u.png',
			B: 'img/frames/planeswalker/tall-borderless/b.png',
			R: 'img/frames/planeswalker/tall-borderless/r.png',
			G: 'img/frames/planeswalker/tall-borderless/g.png',
			M: 'img/frames/planeswalker/tall-borderless/m.png',
			A: 'img/frames/planeswalker/tall-borderless/a.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A', L: 'A' },
		layout: {
			artwork: { dragTop: 0, dragBottom: 1922 },
			title: { x: 130, y: 136, maxWidth: 1240, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1100, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1172, width: 1100, height: 698, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1099, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-transform-front': {
		id: 'planeswalker-transform-front',
		overlay: {
			path: 'img/frames/planeswalker/transform/sun.svg',
			x: 89,
			y: 79,
			width: 110,
			height: 110,
		},
		frames: {
			W: 'img/frames/planeswalker/transform/wf.png',
			U: 'img/frames/planeswalker/transform/uf.png',
			B: 'img/frames/planeswalker/transform/bf.png',
			R: 'img/frames/planeswalker/transform/rf.png',
			G: 'img/frames/planeswalker/transform/gf.png',
			M: 'img/frames/planeswalker/transform/mf.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, A: 'M', C: 'M', L: 'M' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1180 },
			title: { x: 240, y: 136, maxWidth: 1244, font: '80px belerenb, serif', color: '#111' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#111' },
			type: { x: 130, y: 1239, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1310, width: 1100, height: 560, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1237, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-transform-back': {
		id: 'planeswalker-transform-back',
		overlay: {
			path: 'img/frames/planeswalker/transform/moon.svg',
			x: 89,
			y: 79,
			width: 110,
			height: 110,
		},
		frames: {
			W: 'img/frames/planeswalker/transform/wb.png',
			U: 'img/frames/planeswalker/transform/ub.png',
			B: 'img/frames/planeswalker/transform/bb.png',
			R: 'img/frames/planeswalker/transform/rb.png',
			G: 'img/frames/planeswalker/transform/gb.png',
			M: 'img/frames/planeswalker/transform/mb.png',
		},
		pt: {
			W: 'img/frames/planeswalker/transform/loyalty.png',
			U: 'img/frames/planeswalker/transform/loyalty.png',
			B: 'img/frames/planeswalker/transform/loyalty.png',
			R: 'img/frames/planeswalker/transform/loyalty.png',
			G: 'img/frames/planeswalker/transform/loyalty.png',
			M: 'img/frames/planeswalker/transform/loyalty.png',
		},
		fallbacks: { ...commonFallbacks, A: 'M', C: 'M', L: 'M' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1180 },
			title: { x: 240, y: 136, maxWidth: 1244, font: '80px belerenb, serif', color: '#fff' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#fff' },
			type: { x: 196, y: 1239, maxWidth: 1174, font: '68px belerenb, serif', color: '#fff' },
			rules: { x: 270, y: 1310, width: 1100, height: 560, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1237, boxSize: 80 },
			pt: { x: 1200, y: 1847, width: 228, height: 142, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'planeswalker-mdfc-back': {
		id: 'planeswalker-mdfc-back',
		frames: {
			W: 'img/frames/planeswalker/mdfc/base-w.png',
			U: 'img/frames/planeswalker/mdfc/base-u.png',
			B: 'img/frames/planeswalker/mdfc/base-b.png',
			R: 'img/frames/planeswalker/mdfc/base-r.png',
			G: 'img/frames/planeswalker/mdfc/base-g.png',
			M: 'img/frames/planeswalker/mdfc/base-m.png',
		},
		frameOverlays: {
			W: { path: 'img/frames/planeswalker/mdfc/wb.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
			U: { path: 'img/frames/planeswalker/mdfc/ub.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
			B: { path: 'img/frames/planeswalker/mdfc/bb.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
			R: { path: 'img/frames/planeswalker/mdfc/rb.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
			G: { path: 'img/frames/planeswalker/mdfc/gb.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
			M: { path: 'img/frames/planeswalker/mdfc/mb.png', crops: [{ x: 30, y: 45, width: 1440, height: 160 }, { x: 40, y: 1835, width: 650, height: 145 }] },
		},
		pt: {},
		fallbacks: { ...commonFallbacks, A: 'M', C: 'M', L: 'M' },
		layout: {
			artwork: { dragTop: 212, dragBottom: 1050 },
			title: { x: 242, y: 136, maxWidth: 1130, font: '80px belerenb, serif', color: '#fff' },
			mana: { right: 1394, centerY: 136, symbolSize: 71, gap: 0, font: '48px belerenb, serif', color: '#fff' },
			type: { x: 130, y: 1100, maxWidth: 1240, font: '68px belerenb, serif', color: '#111' },
			rules: { x: 270, y: 1172, width: 1100, height: 698, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 74, minFontSize: 32 },
			symbol: { centerX: 1340, centerY: 1099, boxSize: 80 },
			pt: { x: 1209, y: 1894, width: 210, height: 78, textX: 1314, textY: 1933, font: '78px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'token-regular': {
		id: 'token-regular',
		frames: tokenFrames('regular', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C', 'L']),
		pt: m15Pt,
		fallbacks: commonFallbacks,
		layout: tokenRegularLayout,
		fonts: commonFonts,
	},
	'token-tall': {
		id: 'token-tall',
		frames: tokenFrames('tall', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C', 'L']),
		pt: m15Pt,
		fallbacks: commonFallbacks,
		layout: tokenTallLayout,
		fonts: commonFonts,
	},
	'token-short': {
		id: 'token-short',
		frames: tokenFrames('short', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C']),
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, L: 'M' },
		layout: tokenShortLayout,
		fonts: commonFonts,
	},
	'token-textless': {
		id: 'token-textless',
		frames: tokenFrames('textless', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C', 'L']),
		pt: m15Pt,
		fallbacks: commonFallbacks,
		layout: tokenTextlessLayout,
		fonts: commonFonts,
	},
	'token-textless-borderless': {
		id: 'token-textless-borderless',
		frames: tokenFrames('textless-borderless', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C']),
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, L: 'M' },
		layout: tokenTextlessBorderlessLayout,
		fonts: commonFonts,
	},
	'token-nyx': {
		id: 'token-nyx',
		frames: tokenFrames('nyx', ['W', 'U', 'B', 'R', 'G', 'M', 'A']),
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, C: 'A', L: 'M' },
		layout: tokenRegularLayout,
		fonts: commonFonts,
	},
	'token-nyx-textless': {
		id: 'token-nyx-textless',
		frames: tokenFrames('nyx-textless', ['W', 'U', 'B', 'R', 'G', 'M', 'A']),
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, C: 'A', L: 'M' },
		layout: tokenTextlessLayout,
		fonts: commonFonts,
	},
	'token-old': {
		id: 'token-old',
		frames: tokenFrames('old', ['W', 'U', 'B', 'R', 'G', 'M', 'A', 'C']),
		pt: {},
		fallbacks: { ...commonFallbacks, L: 'M' },
		layout: tokenOldLayout,
		fonts: ['100px mplantin', '75px mplantin', '75px mplantini'],
	},
	'token-unglued': {
		id: 'token-unglued',
		borderMask: 'img/frames/token/unglued/border.svg',
		defaultBorderStyle: 'silver',
		frames: tokenFrames('unglued', ['W', 'U', 'B', 'R', 'G', 'M', 'A']),
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A', L: 'M' },
		layout: tokenUngluedLayout,
		fonts: ['90px mplantin'],
	},
	'token-monarch': {
		id: 'token-monarch',
		frames: { C: 'img/frames/token/monarch/monarch.png' },
		pt: {},
		fallbacks: {},
		layout: tokenMonarchLayout,
		fonts: commonFonts,
	},
	'token-marker': {
		id: 'token-marker',
		frames: { C: 'img/frames/token/marker/marker.png' },
		pt: {},
		fallbacks: {},
		layout: tokenMarkerLayout,
		fonts: commonFonts,
	},
	'token-initiative': {
		id: 'token-initiative',
		frames: { C: 'img/frames/token/initiative/initiative.png' },
		pt: {},
		fallbacks: {},
		layout: tokenInitiativeLayout,
		fonts: commonFonts,
	},
	'token-day-night': {
		id: 'token-day-night',
		frames: { C: 'img/frames/token/day-night/day-night.png' },
		pt: {},
		fallbacks: {},
		layout: tokenDayNightLayout,
		fonts: commonFonts,
	},
	'token-jumpstart': {
		id: 'token-jumpstart',
		frames: { C: 'img/frames/token/jumpstart/frame.png' },
		pt: {},
		fallbacks: {},
		layout: tokenJumpstartLayout,
		fonts: commonFonts,
	},
	'box-topper': {
		id: 'box-topper',
		frames: {
			W: 'img/frames/m15/boxTopper/m15BoxTopperFrameW.png',
			U: 'img/frames/m15/boxTopper/m15BoxTopperFrameU.png',
			B: 'img/frames/m15/boxTopper/m15BoxTopperFrameB.png',
			R: 'img/frames/m15/boxTopper/m15BoxTopperFrameR.png',
			G: 'img/frames/m15/boxTopper/m15BoxTopperFrameG.png',
			M: 'img/frames/m15/boxTopper/m15BoxTopperFrameM.png',
			A: 'img/frames/m15/boxTopper/m15BoxTopperFrameA.png',
			C: 'img/frames/m15/boxTopper/c.png',
			L: 'img/frames/m15/boxTopper/m15BoxTopperFrameL.png',
			WL: 'img/frames/m15/boxTopper/m15BoxTopperFrameWL.png',
			UL: 'img/frames/m15/boxTopper/m15BoxTopperFrameUL.png',
			BL: 'img/frames/m15/boxTopper/m15BoxTopperFrameBL.png',
			RL: 'img/frames/m15/boxTopper/m15BoxTopperFrameRL.png',
			GL: 'img/frames/m15/boxTopper/m15BoxTopperFrameGL.png',
			ML: 'img/frames/m15/boxTopper/m15BoxTopperFrameML.png',
			V: 'img/frames/m15/boxTopper/m15BoxTopperFrameV.png',
		},
		pt: m15Pt,
		fallbacks: commonFallbacks,
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/regular/m15MaskRules.png',
			pinlineMask: 'img/frames/m15/regular/m15MaskPinlineSuper.png',
			titleMask: 'img/frames/m15/regular/m15MaskTitle.png',
			typeMask: 'img/frames/m15/regular/m15MaskType.png',
			frameMask: 'img/frames/m15/regular/m15MaskFrame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: {
			artwork: { dragTop: 210, dragBottom: 1200 },
			title: { x: 115, y: 160, maxWidth: 1000, font: '70px belerenb, serif', color: '#111' },
			mana: { right: 1390, centerY: 160, symbolSize: 64, gap: 4, font: '48px belerenb, serif', color: '#111' },
			type: { x: 115, y: 1245, maxWidth: 1120, font: '54px belerenb, serif', color: '#fff' },
			rules: { x: 125, y: 1345, width: 1240, height: 555, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1248, boxSize: 85 },
			pt: { x: 1136, y: 1903, width: 282, height: 154, textX: 1295, textY: 1975, font: '70px belerenbsc, serif', color: '#111' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'm15-regular': {
		id: 'm15-regular',
		frames: {
			W: 'img/frames/m15/new/w.png',
			U: 'img/frames/m15/new/u.png',
			B: 'img/frames/m15/new/b.png',
			R: 'img/frames/m15/new/r.png',
			G: 'img/frames/m15/new/g.png',
			M: 'img/frames/m15/new/m.png',
			A: 'img/frames/m15/new/a.png',
			C: 'img/frames/m15/new/c.png',
			L: 'img/frames/m15/new/l.png',
			WL: 'img/frames/m15/new/lw.png',
			UL: 'img/frames/m15/new/lu.png',
			BL: 'img/frames/m15/new/lb.png',
			RL: 'img/frames/m15/new/lr.png',
			GL: 'img/frames/m15/new/lg.png',
			ML: 'img/frames/m15/new/lm.png',
			V: 'img/frames/m15/new/v.png',
		},
		pt: m15Pt,
		fallbacks: commonFallbacks,
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/new/rules.png',
			pinlineMask: 'img/frames/m15/new/pinline.png',
			titleMask: 'img/frames/m15/new/title.png',
			typeMask: 'img/frames/m15/new/type.png',
			frameMask: 'img/frames/m15/new/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: m15RegularLayout,
		fonts: commonFonts,
	},
	'm15-extended': {
		id: 'm15-extended',
		frames: {
			W: 'img/frames/m15/new/extended/w.png',
			U: 'img/frames/m15/new/extended/u.png',
			B: 'img/frames/m15/new/extended/b.png',
			R: 'img/frames/m15/new/extended/r.png',
			G: 'img/frames/m15/new/extended/g.png',
			M: 'img/frames/m15/new/extended/m.png',
			A: 'img/frames/m15/new/extended/a.png',
			C: 'img/frames/m15/new/extended/c.png',
			L: 'img/frames/m15/new/extended/l.png',
			WL: 'img/frames/m15/new/extended/lw.png',
			UL: 'img/frames/m15/new/extended/lu.png',
			BL: 'img/frames/m15/new/extended/lb.png',
			RL: 'img/frames/m15/new/extended/lr.png',
			GL: 'img/frames/m15/new/extended/lg.png',
			ML: 'img/frames/m15/new/extended/lm.png',
			V: 'img/frames/m15/new/extended/v.png',
		},
		pt: m15Pt,
		fallbacks: commonFallbacks,
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/new/rules.png',
			pinlineMask: 'img/frames/m15/new/extended/pinline.png',
			titleMask: 'img/frames/m15/new/title.png',
			typeMask: 'img/frames/m15/new/type.png',
			frameMask: 'img/frames/m15/new/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: {
			artwork: { dragTop: 176, dragBottom: 1318 },
			title: { x: 125, y: 165, maxWidth: 1244, font: '70px belerenb, serif', color: '#111' },
			mana: { right: 1391, centerY: 167, symbolSize: 64, gap: 4, font: '48px belerenb, serif', color: '#111' },
			type: { x: 125, y: 1253, maxWidth: 1244, font: '54px belerenb, serif', color: '#fff' },
			rules: { x: 129, y: 1328, width: 1242, height: 604, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1249, boxSize: 85 },
			pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1292, textY: 1933, font: '70px belerenbsc, serif', color: '#111' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	snow: {
		id: 'snow',
		frames: {
			W: 'img/frames/m15/new/snow/w.png',
			U: 'img/frames/m15/new/snow/u.png',
			B: 'img/frames/m15/new/snow/b.png',
			R: 'img/frames/m15/new/snow/r.png',
			G: 'img/frames/m15/new/snow/g.png',
			M: 'img/frames/m15/new/snow/m.png',
			A: 'img/frames/m15/new/snow/a.png',
			L: 'img/frames/m15/new/snow/l.png',
			WL: 'img/frames/m15/new/snow/lw.png',
			UL: 'img/frames/m15/new/snow/lu.png',
			BL: 'img/frames/m15/new/snow/lb.png',
			RL: 'img/frames/m15/new/snow/lr.png',
			GL: 'img/frames/m15/new/snow/lg.png',
			ML: 'img/frames/m15/new/snow/lm.png',
		},
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, C: 'A' },
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/new/rules.png',
			pinlineMask: 'img/frames/m15/new/pinline.png',
			titleMask: 'img/frames/m15/new/title.png',
			typeMask: 'img/frames/m15/new/type.png',
			frameMask: 'img/frames/m15/new/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: m15RegularLayout,
		fonts: commonFonts,
	},
	nyx: {
		id: 'nyx',
		frames: {
			W: 'img/frames/m15/new/nyx/w.png',
			U: 'img/frames/m15/new/nyx/u.png',
			B: 'img/frames/m15/new/nyx/b.png',
			R: 'img/frames/m15/new/nyx/r.png',
			G: 'img/frames/m15/new/nyx/g.png',
			M: 'img/frames/m15/new/nyx/m.png',
			A: 'img/frames/m15/new/nyx/a.png',
		},
		pt: m15Pt,
		fallbacks: {
			...commonFallbacks,
			C: 'A', L: 'M', WL: 'M', UL: 'M', BL: 'M', RL: 'M', GL: 'M', ML: 'M',
		},
		dual: {
			neutralVariant: 'A',
			rulesMask: 'img/frames/m15/new/rules.png',
			pinlineMask: 'img/frames/m15/new/pinline.png',
			titleMask: 'img/frames/m15/new/title.png',
			typeMask: 'img/frames/m15/new/type.png',
			frameMask: 'img/frames/m15/new/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: m15RegularLayout,
		fonts: commonFonts,
	},
	'universes-beyond': {
		id: 'universes-beyond',
		frames: {
			W: 'img/frames/m15/new/ub/w.png',
			U: 'img/frames/m15/new/ub/u.png',
			B: 'img/frames/m15/new/ub/b.png',
			R: 'img/frames/m15/new/ub/r.png',
			G: 'img/frames/m15/new/ub/g.png',
			M: 'img/frames/m15/new/ub/m.png',
			A: 'img/frames/m15/new/ub/a.png',
			L: 'img/frames/m15/new/ub/l.png',
			WL: 'img/frames/m15/new/ub/lw.png',
			UL: 'img/frames/m15/new/ub/lu.png',
			BL: 'img/frames/m15/new/ub/lb.png',
			RL: 'img/frames/m15/new/ub/lr.png',
			GL: 'img/frames/m15/new/ub/lg.png',
			ML: 'img/frames/m15/new/ub/lm.png',
			V: 'img/frames/m15/new/ub/v.png',
		},
		pt: {
			W: 'img/frames/m15/ub/pt/w.png',
			U: 'img/frames/m15/ub/pt/u.png',
			B: 'img/frames/m15/ub/pt/b.png',
			R: 'img/frames/m15/ub/pt/r.png',
			G: 'img/frames/m15/ub/pt/g.png',
			M: 'img/frames/m15/ub/pt/m.png',
			A: 'img/frames/m15/ub/pt/a.png',
			C: 'img/frames/m15/ub/pt/c.png',
			V: 'img/frames/m15/ub/pt/v.png',
		},
		fallbacks: { ...commonFallbacks, C: 'A' },
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/new/rules.png',
			pinlineMask: 'img/frames/m15/new/pinline.png',
			titleMask: 'img/frames/m15/new/title.png',
			typeMask: 'img/frames/m15/new/type.png',
			frameMask: 'img/frames/m15/new/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: m15RegularLayout,
		fonts: commonFonts,
	},
	borderless: {
		id: 'borderless',
		frames: {
			W: 'img/frames/m15/borderless/m15GenericShowcaseFrameW.png',
			U: 'img/frames/m15/borderless/m15GenericShowcaseFrameU.png',
			B: 'img/frames/m15/borderless/m15GenericShowcaseFrameB.png',
			R: 'img/frames/m15/borderless/m15GenericShowcaseFrameR.png',
			G: 'img/frames/m15/borderless/m15GenericShowcaseFrameG.png',
			M: 'img/frames/m15/borderless/m15GenericShowcaseFrameM.png',
			A: 'img/frames/m15/borderless/m15GenericShowcaseFrameA.png',
			C: 'img/frames/m15/borderless/m15GenericShowcaseFrameC.png',
			L: 'img/frames/m15/borderless/m15GenericShowcaseFrameL.png',
		},
		pt: {
			W: 'img/frames/m15/borderless/pt/w.png',
			U: 'img/frames/m15/borderless/pt/u.png',
			B: 'img/frames/m15/borderless/pt/b.png',
			R: 'img/frames/m15/borderless/pt/r.png',
			G: 'img/frames/m15/borderless/pt/g.png',
			M: 'img/frames/m15/borderless/pt/m.png',
			A: 'img/frames/m15/borderless/pt/a.png',
			C: 'img/frames/m15/borderless/pt/l.png',
		},
		fallbacks: commonFallbacks,
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/m15/regular/m15MaskRules.png',
			pinlineMask: 'img/frames/m15/borderless/m15GenericShowcaseMaskPinline.png',
			titleMask: 'img/frames/m15/regular/m15MaskTitle.png',
			typeMask: 'img/frames/m15/regular/m15MaskType.png',
			frameMask: 'img/frames/m15/regular/m15MaskFrame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: {
			artwork: { dragTop: 210, dragBottom: 1160 },
			title: { x: 128, y: 165, maxWidth: 1244, font: '70px belerenb, serif', color: '#fff' },
			mana: { right: 1391, centerY: 167, symbolSize: 64, gap: 4, font: '48px belerenb, serif', color: '#fff' },
			type: { x: 128, y: 1245, maxWidth: 1244, font: '54px belerenb, serif', color: '#fff' },
			rules: { x: 129, y: 1324, width: 1242, height: 604, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#fff', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1241, boxSize: 85 },
			pt: { x: 1146, y: 1861, width: 274, height: 140, textX: 1283, textY: 1932, font: '70px belerenbsc, serif', color: '#fff' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'promo-regular': {
		id: 'promo-regular',
		frames: {
			W: 'img/frames/promo/regular/m15PromoFrameW.png',
			U: 'img/frames/promo/regular/m15PromoFrameU.png',
			B: 'img/frames/promo/regular/m15PromoFrameB.png',
			R: 'img/frames/promo/regular/m15PromoFrameR.png',
			G: 'img/frames/promo/regular/m15PromoFrameG.png',
			M: 'img/frames/promo/regular/m15PromoFrameM.png',
			A: 'img/frames/promo/regular/m15PromoFrameA.png',
			L: 'img/frames/promo/regular/m15PromoFrameL.png',
		},
		pt: m15Pt,
		fallbacks: { ...commonFallbacks, C: 'A' },
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/promo/m15PromoMaskRules.png',
			pinlineMask: 'img/frames/promo/m15PromoMaskPinline.png',
			titleMask: 'img/frames/m15/regular/m15MaskTitle.png',
			typeMask: 'img/frames/promo/m15PromoMaskType.png',
			frameMask: 'img/frames/m15/regular/m15MaskFrame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: {
			artwork: { dragTop: 210, dragBottom: 1340 },
			title: { x: 128, y: 165, maxWidth: 1244, font: '70px belerenb, serif', color: '#fff' },
			mana: { right: 1391, centerY: 167, symbolSize: 64, gap: 4, font: '48px belerenb, serif', color: '#fff' },
			type: { x: 128, y: 1421, maxWidth: 1244, font: '54px belerenb, serif', color: '#fff' },
			rules: { x: 129, y: 1500, width: 1242, height: 430, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#fff', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1416, boxSize: 85 },
			pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1292, textY: 1933, font: '70px belerenbsc, serif', color: '#111' },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'eighth-edition': {
		id: 'eighth-edition',
		borderMask: 'img/frames/8th/border.png',
		frames: {
			W: 'img/frames/8th/w.png',
			U: 'img/frames/8th/u.png',
			B: 'img/frames/8th/b.png',
			R: 'img/frames/8th/r.png',
			G: 'img/frames/8th/g.png',
			M: 'img/frames/8th/m.png',
			A: 'img/frames/8th/a.png',
			C: 'img/frames/8th/c.png',
			L: 'img/frames/8th/l.png',
			WL: 'img/frames/8th/wl.png',
			UL: 'img/frames/8th/ul.png',
			BL: 'img/frames/8th/bl.png',
			RL: 'img/frames/8th/rl.png',
			GL: 'img/frames/8th/gl.png',
			ML: 'img/frames/8th/ml.png',
		},
		pt: {
			W: 'img/frames/8th/pt/w.png',
			U: 'img/frames/8th/pt/u.png',
			B: 'img/frames/8th/pt/b.png',
			R: 'img/frames/8th/pt/r.png',
			G: 'img/frames/8th/pt/g.png',
			M: 'img/frames/8th/pt/m.png',
			A: 'img/frames/8th/pt/a.png',
			C: 'img/frames/8th/pt/l.png',
		},
		fallbacks: commonFallbacks,
		dual: {
			neutralVariant: 'L',
			rulesMask: 'img/frames/8th/rules.png',
			pinlineMask: 'img/frames/8th/pinline.png',
			titleMask: 'img/frames/8th/title.png',
			typeMask: 'img/frames/8th/type.png',
			frameMask: 'img/frames/8th/frame.png',
			rightHalfMask: 'img/frames/m15/regular/maskRightHalf.png',
		},
		layout: {
			artwork: { dragTop: 254, dragBottom: 1162 },
			title: { x: 135, y: 177, maxWidth: 1236, font: '74px matrixb, serif', color: '#111' },
			mana: { right: 1372, centerY: 177, symbolSize: 64, gap: 4, font: '48px matrixb, serif', color: '#111' },
			type: { x: 153, y: 1230, maxWidth: 1195, font: '62px matrixb, serif', color: '#111' },
			rules: { x: 153, y: 1328, width: 1191, height: 544, fontFamily: 'mplantin', verticalAlign: 'middle', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1325, centerY: 1236, boxSize: 82 },
			pt: { x: 1090, y: 1852, width: 309, height: 163, textX: 1253, textY: 1928, font: '80px matrixbsc, serif', color: '#111' },
			footer: {
				x: 112,
				maxWidth: 1216,
				metadataY: 1940,
				metadata: { font: '36px matrixb, serif', color: '#111' },
				disclaimerY: 1990,
				disclaimer: { font: '30px mplantin, serif', color: '#111' },
				colorByVariant: { B: '#fff', L: '#fff', WL: '#fff', UL: '#fff', BL: '#fff', RL: '#fff', GL: '#fff', ML: '#fff' },
			},
		},
		fonts: ['68px matrixb', '70px matrixbsc', '64px mplantin', '64px mplantini'],
	},
	'seventh-edition': {
		id: 'seventh-edition',
		borderMask: 'img/frames/seventh/border.svg',
		frames: {
			W: 'img/frames/seventh/w.png',
			U: 'img/frames/seventh/u.png',
			B: 'img/frames/seventh/b.png',
			R: 'img/frames/seventh/r.png',
			G: 'img/frames/seventh/g.png',
			M: 'img/frames/seventh/m.png',
			A: 'img/frames/seventh/a.png',
			C: 'img/frames/seventh/c.png',
			L: 'img/frames/seventh/l.png',
			WL: 'img/frames/seventh/wl.png',
			UL: 'img/frames/seventh/ul.png',
			BL: 'img/frames/seventh/bl.png',
			RL: 'img/frames/seventh/rl.png',
			GL: 'img/frames/seventh/gl.png',
		},
		pt: {},
		fallbacks: commonFallbacks,
		layout: { ...seventhLayout, mana: { ...seventhLayout.mana, shadowColor: '#111', shadowOffsetX: 0, shadowOffsetY: 0 } },
		fonts: ['86px goudymedieval', '67px goudymedieval', '72px mplantin', '72px mplantini'],
	},
	'old-floating': {
		id: 'old-floating',
		frames: {
			W: 'img/frames/old/floating/w.png',
			U: 'img/frames/old/floating/u.png',
			B: 'img/frames/old/floating/b.png',
			R: 'img/frames/old/floating/r.png',
			G: 'img/frames/old/floating/g.png',
			M: 'img/frames/old/floating/m.png',
			A: 'img/frames/old/floating/a.png',
			C: 'img/frames/old/floating/c.png',
			L: 'img/frames/old/floating/l.png',
			WL: 'img/frames/old/floating/land/w.png',
			UL: 'img/frames/old/floating/land/u.png',
			BL: 'img/frames/old/floating/land/b.png',
			RL: 'img/frames/old/floating/land/r.png',
			GL: 'img/frames/old/floating/land/g.png',
		},
		pt: {},
		fallbacks: commonFallbacks,
		layout: { ...seventhLayout, mana: { ...seventhLayout.mana, shadowOffsetX: 0, shadowOffsetY: 0 }, footer: { ...seventhLayout.footer, metadataY: 1915, disclaimerY: 1965 } },
		fonts: ['80px goudymedieval', '65px goudymedieval', '72px mplantin', '72px mplantini'],
	},
	abu: {
		id: 'abu',
		borderMask: 'img/frames/old/abu/border.svg',
		dualLandMask: 'img/frames/old/abu/dualLand.png',
		manaSymbolOverrides: {
			'w.svg': 'old/oldw.svg', 'u.svg': 'old/oldu.svg', 'b.svg': 'old/oldb.svg',
			'r.svg': 'old/oldr.svg', 'g.svg': 'old/oldg.svg',
		},
		frames: abuFrames,
		pt: {},
		fallbacks: abuFallbacks,
		layout: abuLayout,
		fonts: ['90px goudymedieval', '87px mplantin', '72px mplantini'],
	},
	revised: {
		id: 'revised',
		borderMask: 'img/frames/old/abu/border.svg',
		defaultBorderStyle: 'white',
		dualLandMask: 'img/frames/old/abu/dualLand.png',
		manaSymbolOverrides: {
			'w.svg': 'old/oldw.svg', 'u.svg': 'old/oldu.svg', 'b.svg': 'old/oldb.svg',
			'r.svg': 'old/oldr.svg', 'g.svg': 'old/oldg.svg', 't.svg': 'originaltap.svg',
		},
		frames: abuFrames,
		pt: {},
		fallbacks: abuFallbacks,
		layout: abuLayout,
		fonts: ['90px goudymedieval', '87px mplantin', '72px mplantini'],
	},
	'fourth-era': {
		id: 'fourth-era',
		borderMask: 'img/frames/old/fourth/borderBlack.png',
		baseBorderStyle: 'white',
		defaultBorderStyle: 'white',
		manaSymbolOverrides: { 't.svg': 'oldtap.svg' },
		frames: {
			W: 'img/frames/old/fourth/w.png', U: 'img/frames/old/fourth/u.png',
			B: 'img/frames/old/fourth/b.png', R: 'img/frames/old/fourth/r.png',
			G: 'img/frames/old/fourth/g.png', M: 'img/frames/old/fourth/m.png',
			A: 'img/frames/old/fourth/a.png', L: 'img/frames/old/fourth/l.png',
		},
		pt: {},
		fallbacks: { ...commonFallbacks, C: 'A' },
		layout: {
			artwork: { dragTop: 186, dragBottom: 1140 },
			title: { x: 124, y: 112, maxWidth: 1252, font: '86px goudymedieval, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			mana: { right: 1386, centerY: 112, symbolSize: 72, gap: 4, font: '48px mplantin, serif', color: '#fff' },
			type: { x: 124, y: 1209, maxWidth: 1252, font: '67px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			rules: { x: 192, y: 1274, width: 1116, height: 572, verticalAlign: 'middle', fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 72, minFontSize: 32 },
			symbol: { centerX: 1310, centerY: 1209, boxSize: 76 },
			pt: { x: 1230, y: 1902, width: 205, height: 90, textX: 1332, textY: 1947, font: '90px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			footer: {
				align: 'left', x: 150, maxWidth: 1200,
				metadataY: 1925, metadata: { font: '40px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 2 },
				disclaimerY: 1990, disclaimer: { font: '26px mplantin, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 2, shadowOffsetY: 2 },
			},
		},
		fonts: ['86px goudymedieval', '90px mplantin', '72px mplantini'],
	},
	colorshifted: {
		id: 'colorshifted',
		frames: {
			W: 'img/frames/m15/colorshifted/w.png', U: 'img/frames/m15/colorshifted/u.png',
			B: 'img/frames/m15/colorshifted/b.png', R: 'img/frames/m15/colorshifted/r.png',
			G: 'img/frames/m15/colorshifted/g.png',
		},
		pt: {
			W: 'img/frames/m15/colorshifted/wpt.png', U: 'img/frames/m15/colorshifted/upt.png',
			B: 'img/frames/m15/colorshifted/bpt.png', R: 'img/frames/m15/colorshifted/rpt.png',
			G: 'img/frames/m15/colorshifted/gpt.png',
		},
		fallbacks: {
			M: 'W', A: 'W', C: 'W', L: 'W', V: 'W',
			WL: 'W', UL: 'W', BL: 'W', RL: 'W', GL: 'W', ML: 'W',
			WU: 'W', WB: 'W', UB: 'W', UR: 'W', BR: 'W', BG: 'W', RG: 'W', RW: 'W', GW: 'W', GU: 'W',
		},
		layout: {
			artwork: { dragTop: 237, dragBottom: 1167 },
			title: { x: 128, y: 167, maxWidth: 1244, font: '78px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			mana: { right: 1394, centerY: 164, symbolSize: 71, gap: 4, font: '48px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 1, shadowOffsetY: 10 },
			type: { x: 128, y: 1246, maxWidth: 1244, font: '64px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			rules: { x: 129, y: 1324, width: 1242, height: 604, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 64, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1248, boxSize: 85 },
			pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1292, textY: 1933, font: '70px belerenbsc, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	classicshifted: {
		id: 'classicshifted',
		frames: {
			W: 'img/frames/custom/classicshifted/w.png', U: 'img/frames/custom/classicshifted/u.png',
			B: 'img/frames/custom/classicshifted/b.png', R: 'img/frames/custom/classicshifted/r.png',
			G: 'img/frames/custom/classicshifted/g.png', M: 'img/frames/custom/classicshifted/m.png',
			A: 'img/frames/custom/classicshifted/a.png', C: 'img/frames/custom/classicshifted/c.png',
			L: 'img/frames/custom/classicshifted/l.png', WL: 'img/frames/custom/classicshifted/wl.png',
			UL: 'img/frames/custom/classicshifted/ul.png', BL: 'img/frames/custom/classicshifted/bl.png',
			RL: 'img/frames/custom/classicshifted/rl.png', GL: 'img/frames/custom/classicshifted/gl.png',
		},
		pt: {
			W: 'img/frames/custom/classicshifted/ptW.png', U: 'img/frames/custom/classicshifted/ptU.png',
			B: 'img/frames/custom/classicshifted/ptB.png', R: 'img/frames/custom/classicshifted/ptR.png',
			G: 'img/frames/custom/classicshifted/ptG.png', M: 'img/frames/custom/classicshifted/ptM.png',
			A: 'img/frames/custom/classicshifted/ptA.png', C: 'img/frames/custom/classicshifted/ptC.png',
			L: 'img/frames/custom/classicshifted/ptL.png',
		},
		fallbacks: commonFallbacks,
		layout: {
			artwork: { dragTop: 200, dragBottom: 1177 },
			title: { x: 128, y: 132, maxWidth: 1244, font: '80px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			mana: { right: 1394, centerY: 132, symbolSize: 71, gap: 4, font: '48px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: -2, shadowOffsetY: 6 },
			type: { x: 128, y: 1254, maxWidth: 1244, font: '68px belerenb, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			rules: { x: 129, y: 1329, width: 1242, height: 610, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 76, minFontSize: 32 },
			symbol: { centerX: 1335, centerY: 1251, boxSize: 85 },
			pt: { x: 1136, y: 1858, width: 282, height: 154, textX: 1292, textY: 1933, font: '78px belerenbsc, serif', color: '#fff', shadowColor: '#111', shadowOffsetX: 3, shadowOffsetY: 3 },
			footer: commonFooter,
		},
		fonts: commonFonts,
	},
	'future-sight': {
		id: 'future-sight',
		frames: {
			W: 'img/frames/future/regular/futureFrameW.png', U: 'img/frames/future/regular/futureFrameU.png',
			B: 'img/frames/future/regular/futureFrameB.png', R: 'img/frames/future/regular/futureFrameR.png',
			G: 'img/frames/future/regular/futureFrameG.png', M: 'img/frames/future/regular/futureFrameM.png',
			A: 'img/frames/future/regular/futureFrameA.png', L: 'img/frames/future/regular/futureFrameL.png',
			C: 'img/frames/future/regular/futureFrameC.png',
		},
		pt: {
			W: 'img/frames/future/regular/futurePTW.png', U: 'img/frames/future/regular/futurePTU.png',
			B: 'img/frames/future/regular/futurePTB.png', R: 'img/frames/future/regular/futurePTR.png',
			G: 'img/frames/future/regular/futurePTG.png', M: 'img/frames/future/regular/futurePTM.png',
			A: 'img/frames/future/regular/futurePTA.png', L: 'img/frames/future/regular/futurePTL.png',
			C: 'img/frames/future/regular/futurePTC.png',
		},
		typeIconMasks: {
			creature: 'img/frames/future/futureMaskCreature.png',
			instant: 'img/frames/future/futureMaskInstant.png',
			sorcery: 'img/frames/future/futureMaskSorcery.png',
			enchantment: 'img/frames/future/futureMaskEnchantment.png',
			artifact: 'img/frames/future/futureMaskArtifact.png',
			land: 'img/frames/future/futureMaskLand.png',
			multi: 'img/frames/future/futureMaskMulti.png',
		},
		fallbacks: commonFallbacks,
		layout: {
			artwork: { dragTop: 177, dragBottom: 1179 },
			title: { x: 264, y: 166, maxWidth: 1070, font: '90px matrixb, serif', color: '#fff', colorByVariant: { W: '#111', A: '#111', C: '#111' } },
			mana: { right: 1390, centerY: 166, symbolSize: 117, gap: 4, font: '48px matrixb, serif', color: '#fff', verticalPositions: [[184, 283], [123, 419], [93, 568], [93, 720], [119, 883], [214, 1035]] },
			type: { x: 182, y: 1239, maxWidth: 1148, font: '74px matrixb, serif', color: '#fff', colorByVariant: { W: '#111', A: '#111', C: '#111' } },
			rules: { x: 154, y: 1312, width: 1211, height: 554, fontFamily: 'mplantin', italicFontFamily: 'mplantini', color: '#111', strokeColor: '#111', strokeWidth: 0.75, maxFontSize: 72, minFontSize: 32 },
			symbol: { centerX: 1368, centerY: 1248, boxSize: 80 },
			pt: { x: 1143, y: 1855, width: 260, height: 164, textX: 1273, textY: 1941, font: '80px matrixbsc, serif', color: '#fff', colorByVariant: { W: '#111', A: '#111', C: '#111' } },
			footer: {
				align: 'right', x: 1100, maxWidth: 950,
				metadataY: 1931, metadata: { font: '42px matrixb, serif', color: '#fff' },
				disclaimerY: 1990, disclaimer: { font: '28px mplantin, serif', color: '#fff' },
				colorByVariant: { W: '#111', A: '#111', C: '#111' },
			},
		},
		fonts: ['94px matrixb', '80px matrixbsc', '72px mplantin', '72px mplantini'],
	},
}
